#pragma checksum "BusP.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "149E43D2A4E1CED162C19DDC2F3C881B96E05DEC"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RoutingClientTM;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace RoutingClientTM {
    
    
    /// <summary>
    /// BusP
    /// </summary>
    public partial class BusP : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 40 "BusP.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox regTxt;
        
        #line default
        #line hidden
        
        
        #line 43 "BusP.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox busTypeBox;
        
        #line default
        #line hidden
        
        
        #line 51 "BusP.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox yearTxt;
        
        #line default
        #line hidden
        
        
        #line 54 "BusP.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox capacityTxt;
        
        #line default
        #line hidden
        
        
        #line 57 "BusP.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox modelTypeBox;
        
        #line default
        #line hidden
        
        
        #line 61 "BusP.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox weightTxt;
        
        #line default
        #line hidden
        
        
        #line 66 "BusP.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox tachoTypeBox;
        
        #line default
        #line hidden
        
        
        #line 72 "BusP.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox busList;
        
        #line default
        #line hidden
        
        
        #line 83 "BusP.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox heightTxt;
        
        #line default
        #line hidden
        
        
        #line 86 "BusP.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox widthTxt;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/RoutingClientTM;component/busp.xaml", System.UriKind.Relative);
            
            #line 1 "BusP.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.regTxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 2:
            this.busTypeBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 3:
            this.yearTxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.capacityTxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.modelTypeBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.weightTxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.tachoTypeBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 8:
            this.busList = ((System.Windows.Controls.ListBox)(target));
            
            #line 72 "BusP.xaml"
            this.busList.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.BusList_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 9:
            this.heightTxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.widthTxt = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

