#pragma checksum "Login.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "A63BDED18C5A03C0F93CEECA9D4833EE382D303D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RoutingClientTM;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace RoutingClientTM {
    
    
    /// <summary>
    /// Login
    /// </summary>
    public partial class Login : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 33 "Login.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle rectMid;
        
        #line default
        #line hidden
        
        
        #line 49 "Login.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle topMid;
        
        #line default
        #line hidden
        
        
        #line 52 "Login.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox usernameTxt;
        
        #line default
        #line hidden
        
        
        #line 55 "Login.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox passTxt;
        
        #line default
        #line hidden
        
        
        #line 57 "Login.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button loginBtn;
        
        #line default
        #line hidden
        
        
        #line 59 "Login.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image loginImg;
        
        #line default
        #line hidden
        
        
        #line 60 "Login.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock loginTxt;
        
        #line default
        #line hidden
        
        
        #line 64 "Login.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Rectangle rectBot;
        
        #line default
        #line hidden
        
        
        #line 67 "Login.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image closeBtn;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/RoutingClientTM;component/login.xaml", System.UriKind.Relative);
            
            #line 1 "Login.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.rectMid = ((System.Windows.Shapes.Rectangle)(target));
            
            #line 33 "Login.xaml"
            this.rectMid.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.RectMid_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.topMid = ((System.Windows.Shapes.Rectangle)(target));
            
            #line 49 "Login.xaml"
            this.topMid.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.RectMid_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 3:
            this.usernameTxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.passTxt = ((System.Windows.Controls.PasswordBox)(target));
            return;
            case 5:
            this.loginBtn = ((System.Windows.Controls.Button)(target));
            
            #line 57 "Login.xaml"
            this.loginBtn.MouseEnter += new System.Windows.Input.MouseEventHandler(this.LoginBtn_MouseEnter);
            
            #line default
            #line hidden
            
            #line 57 "Login.xaml"
            this.loginBtn.MouseLeave += new System.Windows.Input.MouseEventHandler(this.LoginBtn_MouseLeave);
            
            #line default
            #line hidden
            
            #line 57 "Login.xaml"
            this.loginBtn.Click += new System.Windows.RoutedEventHandler(this.LoginBtn_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.loginImg = ((System.Windows.Controls.Image)(target));
            return;
            case 7:
            this.loginTxt = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.rectBot = ((System.Windows.Shapes.Rectangle)(target));
            
            #line 64 "Login.xaml"
            this.rectBot.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.RectMid_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 9:
            this.closeBtn = ((System.Windows.Controls.Image)(target));
            
            #line 67 "Login.xaml"
            this.closeBtn.MouseEnter += new System.Windows.Input.MouseEventHandler(this.CloseBtn_MouseEnter);
            
            #line default
            #line hidden
            
            #line 67 "Login.xaml"
            this.closeBtn.MouseLeave += new System.Windows.Input.MouseEventHandler(this.CloseBtn_MouseLeave);
            
            #line default
            #line hidden
            
            #line 67 "Login.xaml"
            this.closeBtn.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.CloseBtn_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

