#pragma checksum "Users.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "CACAF9E41D0616AA2457ED106A9A6D4AB5D8A8E0"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RoutingClientTM;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace RoutingClientTM {
    
    
    /// <summary>
    /// Users
    /// </summary>
    public partial class Users : System.Windows.Controls.Page, System.Windows.Markup.IComponentConnector {
        
        
        #line 34 "Users.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image closeBtn;
        
        #line default
        #line hidden
        
        
        #line 41 "Users.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox userIdTxt;
        
        #line default
        #line hidden
        
        
        #line 44 "Users.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox userTypeBox;
        
        #line default
        #line hidden
        
        
        #line 50 "Users.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox fNameTxt;
        
        #line default
        #line hidden
        
        
        #line 53 "Users.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox sNameTxt;
        
        #line default
        #line hidden
        
        
        #line 56 "Users.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox driverTypeBox;
        
        #line default
        #line hidden
        
        
        #line 63 "Users.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox licenseTypeBox;
        
        #line default
        #line hidden
        
        
        #line 69 "Users.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cpcTypeBox;
        
        #line default
        #line hidden
        
        
        #line 75 "Users.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox userList;
        
        #line default
        #line hidden
        
        
        #line 87 "Users.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox emailTxt;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/RoutingClientTM;component/users.xaml", System.UriKind.Relative);
            
            #line 1 "Users.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.closeBtn = ((System.Windows.Controls.Image)(target));
            
            #line 34 "Users.xaml"
            this.closeBtn.MouseEnter += new System.Windows.Input.MouseEventHandler(this.closeBtn_MouseEnter);
            
            #line default
            #line hidden
            
            #line 34 "Users.xaml"
            this.closeBtn.MouseLeave += new System.Windows.Input.MouseEventHandler(this.closeBtn_MouseLeave);
            
            #line default
            #line hidden
            
            #line 34 "Users.xaml"
            this.closeBtn.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.closeBtn_MouseDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.userIdTxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.userTypeBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 4:
            this.fNameTxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.sNameTxt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.driverTypeBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 7:
            this.licenseTypeBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 8:
            this.cpcTypeBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 9:
            this.userList = ((System.Windows.Controls.ListBox)(target));
            
            #line 75 "Users.xaml"
            this.userList.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.UserList_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 10:
            this.emailTxt = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

